name = "Luna_Hang"
author = "MatriXCV"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59a389ac850ca3df1e365fac90b2ed5c2bdea327d3ed7883415c7125b432a9d0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
