name = "Luna_Hang"
author = "MatriXCV"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4bdb4371015a5bd6c900897dbd730c6e2a69c26ff9482a56e07ba742afc210e3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
